// lib/job-matching/mock-jobs.js
// Mock job listings to provide a fallback when APIs are unavailable.

export const MOCK_JOBS = [
    {
        title: "Senior Full Stack Engineer",
        company: "TechNova Solutions",
        location: "Remote",
        experienceLevel: "Senior",
        skillsRequired: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
        industry: "IT / Software Developer",
        salaryRange: "$140,000 - $180,000",
        description: "Leading the development of our core cloud-based platform. We are looking for an experienced engineer who can bridge the gap between frontend performance and backend scalability.",
        applicationUrl: "https://example.com/jobs/1",
        postedDate: new Date(),
        externalJobId: "mock_1",
        source: "mock",
        isRemote: true,
        jobType: "full-time",
    },
    {
        title: "AI Reseach Scientist",
        company: "NeuralNet Labs",
        location: "San Francisco, CA",
        experienceLevel: "Senior",
        skillsRequired: ["Python", "PyTorch", "TensorFlow", "NLP", "Machine Learning"],
        industry: "AI / Machine Learning",
        salaryRange: "$160,000 - $220,000",
        description: "Help us build the next generation of Large Language Models. You will focus on optimizing inference speed and fine-tuning models for specific domain expertise.",
        applicationUrl: "https://example.com/jobs/2",
        postedDate: new Date(),
        externalJobId: "mock_2",
        source: "mock",
        isRemote: false,
        jobType: "full-time",
    },
    {
        title: "Frontend Developer (React)",
        company: "Creative Digital",
        location: "New York, NY",
        experienceLevel: "Mid-Level",
        skillsRequired: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
        industry: "IT / Software Developer",
        salaryRange: "$110,000 - $145,000",
        description: "Join our boutique agency to build stunning, high-performance web applications for global brands. You should have an eye for design and a passion for micro-animations.",
        applicationUrl: "https://example.com/jobs/3",
        postedDate: new Date(),
        externalJobId: "mock_3",
        source: "mock",
        isRemote: true,
        jobType: "full-time",
    },
    {
        title: "Cloud Infrastructure Engineer",
        company: "CloudScale Systems",
        location: "Austin, TX",
        experienceLevel: "Mid-Level",
        skillsRequired: ["AWS", "Terraform", "Kubernetes", "Docker", "Python"],
        industry: "Cloud / DevOps",
        salaryRange: "$125,000 - $160,000",
        description: "Optimizing multi-region infrastructure for a high-traffic e-commerce platform. Focus on reliability, scalability, and cost-optimization using IaC.",
        applicationUrl: "https://example.com/jobs/4",
        postedDate: new Date(),
        externalJobId: "mock_4",
        source: "mock",
        isRemote: true,
        jobType: "full-time",
    },
    {
        title: "Cyber Security Analyst",
        company: "Guardian Defense",
        location: "Washington, DC",
        experienceLevel: "Junior",
        skillsRequired: ["Networking", "Security", "Penetration Testing", "Linux"],
        industry: "Cyber Security",
        salaryRange: "$85,000 - $115,000",
        description: "Monitoring and securing our internal networks. You will perform regular vulnerability scans and participate in incident response drills.",
        applicationUrl: "https://example.com/jobs/5",
        postedDate: new Date(),
        externalJobId: "mock_5",
        source: "mock",
        isRemote: false,
        jobType: "full-time",
    },
    {
        title: "Backend Engineer (Go)",
        company: "Streamline Fintech",
        location: "Remote",
        experienceLevel: "Mid-Level",
        skillsRequired: ["Go", "gRPC", "Microservices", "Redis", "Docker"],
        industry: "IT / Software Developer",
        salaryRange: "$130,000 - $170,000",
        description: "Building low-latency financial transaction processing systems. We use Go for performance and gRPC for efficient service-to-service communication.",
        applicationUrl: "https://example.com/jobs/6",
        postedDate: new Date(),
        externalJobId: "mock_6",
        source: "mock",
        isRemote: true,
        jobType: "full-time",
    },
    {
        title: "Data Analyst",
        company: "MarketInsights Co.",
        location: "Chicago, IL",
        experienceLevel: "Entry Level",
        skillsRequired: ["Python", "SQL", "Tableau", "Excel", "Pandas"],
        industry: "Data Science",
        salaryRange: "$70,000 - $95,000",
        description: "Turning raw market data into actionable business insights. You will work closely with the marketing and product teams to analyze user behavior.",
        applicationUrl: "https://example.com/jobs/7",
        postedDate: new Date(),
        externalJobId: "mock_7",
        source: "mock",
        isRemote: true,
        jobType: "full-time",
    },
    {
        title: "Junior Java Developer",
        company: "Enterprise Core",
        location: "Seattle, WA",
        experienceLevel: "Junior",
        skillsRequired: ["Java", "Spring Boot", "MySQL", "Git"],
        industry: "IT / Software Developer",
        salaryRange: "$80,000 - $110,000",
        description: "Great entry-level opportunity for someone who wants to learn enterprise software development at scale. Mentorship and training provided.",
        applicationUrl: "https://example.com/jobs/8",
        postedDate: new Date(),
        externalJobId: "mock_8",
        source: "mock",
        isRemote: false,
        jobType: "full-time",
    }
];
